# Generated by Django 3.1.4 on 2021-08-28 15:14

from django.db import migrations

import clients.russian_fields_fixed


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=clients.russian_fields_fixed.FixedINNBusinessField(mode='legal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=clients.russian_fields_fixed.FixedKPPField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='ogrn',
            field=clients.russian_fields_fixed.FixedOGRNField(),
        ),
    ]
